### ISSUE TITLE
RIPPER

### ISSUE THREAD

**Issue by simpleme201** [edditdev/veety#1]
be very careful with this scammers guys

**Comment by edditdev** [comment]
its free o.O

**Comment by StellarBot123** [comment]
why its impossible to build ? that crazy whe cant do nothing

**Comment by edditdev** [comment]
> why its impossible to build ? that crazy whe cant do nothing

VEETY Is not available anymore i moved project to versal.pw | what is not open source anymore. If you need VEETY to educate with src, i can provide it to you.

You can't build it now cuz it's encrypted.
